name: GitHub Classroom Workflow

on:
  push:
    branches: [main, develop, deploy2]
  pull_request:
    branches: [main, develop, deploy2]

jobs:
  unit-tests:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run unit tests
        run: |
          pytest -vs ticket_service/app/unit_tests/ticket.py
          pytest -vs flight_service/app/unit_tests/flight.py

  deploy:
    name: Deploy to local Windows via SSH
    needs: [unit-tests]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Copy project to local machine
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: "."
          target: "C:/Users/${{ secrets.SSH_USERNAME }}/rsoi_lab2"

      - name: Run docker-compose on local machine
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd "C:/Users/${{ secrets.SSH_USERNAME }}/rsoi_lab2/docker-compose"
            docker-compose down || echo "No containers running"
            docker-compose up -d --build

  autograding:
    name: Run API tests
    needs: [deploy]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run Postman API tests
        run: |
          npm install -g newman
          newman run v1/postman/collection.json -e v1/postman/environment.json --delay-request 100 --reporters cli
